coveo/dependency-allowed-licenses

private-distributed.yml
private-undistributed.yml
public.yml

* Sort lists
+ Add licenses to our private undistributed allow list
J:DEF-623

Add a few licenses to our allow-licenses lists

---

private-undistributed.yml

Requesting the license union of fonttools since each of them are allowed. 
It seems not scalable to be forced to request each new encountered union.
cc: @alhains @mariob316

[RECS-764] Adding `fonttools` license union

---

private-distributed.yml
private-undistributed.yml
public.yml

Added the missing combinaisons

---

private-undistributed.yml

Add missing combination of allowed licenses

---

private-undistributed.yml

Update private-undistributed.yml J:DEF-160

---

private-undistributed.yml

J: ML-1580
Hopefully this is alright, i figured it was ok since its a conjunction of two allowed licenses. 
I wonder if theres any way to specify that any conjunction of allowed licenses should be automatically allowed 🤔

Allow MIT AND MIT-0

---

private-distributed.yml

Adding the combination of allowed licenses to enable usage on the private distributed Barca project

+ Apache-2.0 & MIT into private-distributed

---

private-undistributed.yml

More licenses, more fun (right?)

More licenses allowed

---

private-undistributed.yml

Those licenses are individually approved

Add another license combination

---

private-undistributed.yml

Triggered by dep review here: https://github.com/coveo-platform/customer-service-api/pull/808

feat: add missing apache license

---

private-undistributed.yml

See https://github.com/coveo-platform/coveo-scala-commons/pull/1426

Add Apache-2.0 AND EPL-1.0 AND EPL-2.0 mixed license

---

private-undistributed.yml

I admit this feels rather silly but I'm not aware of another way to manage this.
Also please note that I'm adding the `xpp` license here, which appears legit but should be reviewed: https://spdx.org/licenses/xpp.html

Various permutations

---

private-undistributed.yml

I have this combination when using Sagemaker, seem like just another mIt license..
https://github.com/coveo-platform/ml-build-agent-sagemaker/actions/runs/11554599784

add mit cmu

---

private-undistributed.yml

See https://github.com/coveo-platform/aws-mac-networking/actions/runs/11915774733

Add a new valid combinaison of licenses

---

public.yml

J:DEF-160
Same as PR https://github.com/coveo/dependency-allowed-licenses/pull/61, forgot to do the same in the configuration for public packages.
Fails in plasma public repo https://github.com/coveo/plasma/actions/runs/12236725805?pr=3978

add 0BSD AND ISC AND MIT to public.yml

---

private-undistributed.yml

See https://github.com/coveo-platform/rd-people/actions/runs/12982514049 & https://github.com/coveo-platform/rd-people/pull/750
All the individual licenses are accepted, this is an additional combination.

feat: add vite license

---

private-distributed.yml

Reverts coveo/dependency-allowed-licenses#66

Revert "Update private-distributed.yml"

---

private-undistributed.yml

Detected in https://github.com/coveo-platform/proxy/pull/1670

feat: Allow new license

---

private-undistributed.yml

fix: add error_prone_annotations to allowed dependencies list

---

private-undistributed-v2.yml
private-undistributed.yml

Got a dependency review issue here: https://github.com/coveo-platform/coveo-cloud-utils/actions/runs/15469206923/job/43549085583?pr=388#step:8:19
Checked the licenses, and it really is EPL-2.0. Don't know why it's detected to something else.

fix(license): Add aspectjweaver to allow list [FOUND-442]

---

private-distributed-v2.yml
private-undistributed-v2.yml

J:FOUND-308
https://github.com/coveo-platform/ratlabservice/pull/593#issuecomment-3096961325

fix(license): add BSD-3-Clause-No-Nuclear-Warranty in allowed licenses

---

private-undistributed.yml

fix: MITNFA missing quote
