coveo/dependency-allowed-licenses

private-distributed.yml
private-undistributed.yml
public.yml

see https://github.com/coveo/indexingpipeline/actions/runs/4959148069/jobs/8872875942?pr=452
` The following dependencies have incompatible licenses:
PythonTests/poetry.lock » exceptiongroup@1.1.1 – License: MIT AND Python-2.0
Error: Dependency review detected incompatible licenses.`

+ 'MIT AND Python-2.0'

---

private-undistributed.yml

Ran into this here:
https://github.com/coveo/org-search-monitoring-service/pull/206
Individually they are already all in the allow list.

new combination of allowed licenses

---

private-distributed.yml

This is currently preventing us from updating the Webpack and TypeScript dependencies in the trainingplatform (aka Level Up) project.

Allow BSD-3-Clause AND BSD-3-Clause-Clear

---

public.yml

Apache-2.0 and MIT are individually allowed, and here: https://github.com/coveo/cli/pull/1315, I have a pkg that uses an Apache-2.0&MIT license.

+ Apache-2.0 & MIT into public

---

private-distributed.yml
private-undistributed.yml
public.yml

Both `MIT` and `ISC` are allowed in every type of package, so the combination of both should be allowed too

chore: add missing combined license

---

private-undistributed.yml

Adding the Ruby license to the undistributed group.
The ruby [license](https://www.ruby-lang.org/en/about/license.txt) is considered open source by most due to its dual licensing scheme.
It also allows modification for software used within the corporation (clause 2.b)
```
2. You may modify your copy of the software in any way, provided that
you do at least ONE of the following:
a) place your modifications in the Public Domain or otherwise
make them Freely Available, such as by posting said
modifications to Usenet or an equivalent medium, or by allowing
the author to include your modifications in the software.
b) use the modified software only within your corporation or
organization.
c) give non-standard binaries non-standard names, with
instructions on where to get the original software …
```

CSEC-12808 Add ruby to allowed license

---

private-undistributed.yml

[ML-2195](https://coveord.atlassian.net/browse/ML-2195)
License for text-unidecode is messy and triggering false positives. Adding it to the list of approved license definitions.
[ML-2195]: https://coveord.atlassian.net/browse/ML-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding messy artistic + GPL license

---

private-undistributed.yml

Hi there, I recently got blocked from adding this [dependency](https://github.com/snok/asgi-correlation-id/blob/main/LICENSE) due to incompatible license. I'm opening this PR on the off chance that nobody has tried to use this license before, however if it is already rejected pls let me know :) (is there a place I can look to see which licenses have already been accessed and denied?)
Not a lawyer, but theres a few clauses who's risk seems project dependent. (3 and 4). Is there a way to allow licenses on a per-project basis? 
Thanks!

Add BSD-4-Clause license to allowed licenses for private undistributed

---

private-undistributed.yml

License check is failing here: https://github.com/coveo/ml-learning-to-retrieve/pull/16 
Since we have both these licenses allowed already I presume that their conjunction is also allowed?

add BSD-2-Clause AND BSD-4-Clause

---

private-undistributed.yml

`Apache-2.0 WITH LLVM-exception` is tripping up our dependency checker.
The dependency path seems to be `lit` <- `triton` <- `torch` <- `deli-serving`, so it's probably something that'll have to get added to the allowlist for the benefit of all deli projects.

[COMAI-1530] Allow another Apache 2.0 license

---

private-undistributed.yml

Two combination licenses are blocking release of a vulnerability patch [here](https://github.com/coveo-platform/ml-product-profitability/pull/277). These licenses are individually approved.

add combination license

---

private-undistributed.yml

This license restriction came up when were were migrating from a Jenkins job to a Github action for the audit dashboard:
https://github.com/coveo-platform/audit-dashboard/pull/51
`LGPL-3.0-or-later` is already on the list, and if I understand correctly, `openvpn-openssl-exception` loosens the restrictions.
It's coming up on `psycopg2` for postgres

[QA-1479] add openvpn-openssl-exception

---

public.yml

The PR [coveo-platform/ml-reranker#20](https://github.com/coveo-platform/ml-reranker/pull/20) raises [a license infraction:](https://github.com/coveo-platform/ml-reranker/actions/runs/10475279908/job/29011570344?pr=20)
> The validity of the licenses of the dependencies below could not be determined. Ensure that they are valid SPDX licenses:
poetry.lock » appnope@0.1.4 – License: BSD-1-Clause AND BSD-2-Clause AND NOASSERTION
Error: Dependency review could not detect the validity of all licenses.
>  We could not detect a license for the following dependencies:
poetry.lock » pywin32@306
This dependency was introduced by ipykernel, which is a **dev-time** dependency:
```
$ poetry show appnope
name         : appnope
version      : 0.1.4
description  : Disable App Nap on macOS >= 10.9
required …
```

[COMAI-2730] Review license for "BSD-1-Clause AND BSD-2-Clause" (appnope)

---

private-undistributed.yml

This adds a combination of already supported licenses:
0BSD  
Apache-2.0 
BSD-3-Clause  
MIT

Add new valid combination for ruff 0.7.3

---

private-undistributed.yml

For botocore 1.35.59 we need `Apache-2.0 AND MIT AND MPL-2.0`, each already allowed individually.

Add new combination of allowed licenses

---

private-distributed.yml

J:[DEF-160](https://coveord.atlassian.net/browse/DEF-160)
We have a failing renovate PR because of this missing license combination. All three are already in the list individually so I figured the aggregation of the three should be alright.
https://github.com/coveo-platform/admin-ui/actions/runs/12229437331
https://github.com/coveo/plasma/actions/runs/12236725805?pr=3978
[DEF-160]: https://coveord.atlassian.net/browse/DEF-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add 0BSD AND ISC AND MIT to private-distributed.yml

---

public.yml

We got a `Apache-2.0 AND MIT AND MIT-0` license, which is a combination of license we usually accept.
See this project: https://github.com/coveo-platform/ml-build-agent-sagemaker/pull/50

Add yet another combination

---

private-undistributed.yml

Àdd license for a `charset-normalizer` lib, that popped in when updating pytz
My project is private and undistributed.
https://github.com/coveo-platform/ml-build-agent-sagemaker/pull/79

Add LGPL + MIT + MPL Combination

---

private-undistributed.yml

pytz package has updated their license. Their license is not listed in the list of allowed licenses.
Add MIT AND ZPL-2.1 license to the list of allowed licenses.

[ML-3321] Add MIT AND ZPL-2.1 license to the list of private undistributed licenses

---

private-undistributed.yml

Added a new license: `LicenseRef-scancode-public-domain AND Unlicense`. `Unlicense` is already in the list of approved licenses and the other one is public domain.
I also added `0BSD AND ISC AND MIT` which is a combo of already approved licenses

chore: add missing licenses combo

---

private-undistributed.yml

Resolves Issue #88 :
> We cannot approve [Cal-1.0] for private undistributed. Is there a possibility to also remove it from line 319? Do you need to create another PR?

Remove Cal-1.0 license from private-undistributed

---

private-undistributed.yml

Per https://github.com/stleary/JSON-java/blob/master/LICENSE, this library is in the public domain. However, it is not a valid SPDX license so it's getting flagged as `NONE` by clearly defined (ref. https://github.com/clearlydefined/curated-data/pull/26813).
This will resolve this issue by allowing the library specifically.

fix: Allow org.json/json since it's public domain

---

private-undistributed.yml

This [here](https://github.com/coveo-platform/ops-module/actions/runs/14841616807) check failed in my PR.
I think that particular [license](https://github.com/python-pillow/Pillow/blob/main/LICENSE) is legit for our use case of undistributed internal tooling.

chore: exclusion for pillow

---

.github/CODEOWNERS
private-undistributed-v2.yml

https://coveord.atlassian.net/browse/DEF-2843
The licence already exists in `private-undistributed.yml`, make it available to `dependency-review-action-v3`.
For https://coveord.atlassian.net/browse/PES-587

feat: add missing licence

---

private-undistributed-v2.yml
public-v2.yml

I have a PR blocked because of a transitive dependency to [nan](https://www.npmjs.com/package/nan) : https://github.com/coveo-platform/boulangerie/actions/runs/15827635678?pr=112
Somehow the license is extracted as `LicenseRef-scancode-dco-1.1 AND MIT`.
https://coveord.atlassian.net/browse/NODEC-55

Add whitelist for "nan" NPM package

---

private-undistributed.yml

- Spicy 1.16 uses this license:
https://github.com/scipy/scipy/blob/main/LICENSES_bundled.txt#L84
- Qhull license details: 
https://github.com/bjnortier/qhull/blob/master/LICENSE
- Dependency review run: 
https://github.com/coveo-platform/cloud-costs/actions/runs/16477597225

fix(FINOPS-2210): Qhull license

---

private-undistributed.yml

https://github.com/coveo-platform/security-cache-metrics-service/pull/802#issuecomment-3218758379
`CC-BY-4.0 AND CC-BY-SA-4.0 AND GPL-2.0-only` is needed and only `CC-BY-SA-4.0` is missing

Adding 'CC-BY-SA-4.0' license to private-undistributed.yml
